name = "HASlib"
uuid = "51f11a40-bb8a-11e8-16ce-adb73741f8e7"
authors = ["Michael Pusterhofer <pusterhofer@student.tugraz.at>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
